### ISSUE TITLE
Libcrypto: Hierarchical tokens

### ISSUE THREAD

**Issue by hzhou0** [chrysalis-blc/libcrypto#5]
Libcrypto should define representations (classes) of tokens, contracts and their hierarchical relationship. 

- [ ] Create function to generate seed from secret words
- [ ] Create token class
- [ ] Create contract class
- [ ] Implement recovery algorithm for transactor accounts
